---
title: "TODO"
output: 
  html_document:
    keep_md: true
---

## Project Milestones:

### Week 5: Research

- finish research and have an idea of how to address the questions in my proposal
  
- find, read, and take notes on related sources
  
- explore related R packages

### Week 6: Begin Coding

- clear up any confusion by asking questions and doing additional research

- start experimenting with code, begin attempting to set up simulations

- have a rough idea of the structure of my code
    
### Week 7: Get Results

- begin to have meaningful observations

- begin creating and organizing important files in the repo

- the majority of code is written, may be in rough stages

- have an idea of some of my answers to my proposed questions and continue to explore unanswered questions
    
### Week 8: Tie Loose Ends 

- clean up and organize code, including any functions

- have clear results and answers to the proposed questions

- if there are any unfinished goals, wrap up and reflect on the progress made

### Week 9: Documentation and Deliverables

- begin formalizing results in an organized and repoducible way in the repo

- gather important code, plots, and data

- begin drafting a report

### Week 10: Documentation and Deliverables

- finalize all documents and code in the repo

- make any final conclusions

- submit final draft of project